-- What's On — initial schema
-- Rebuilt from the 2025-05-05 cluster backup, structure only (no legacy data).
--
-- Column names "desc" and "when" are quoted because they collide with SQL
-- keywords. They are kept as-is so existing app queries keep working.

-- ---------------------------------------------------------------------------
-- venues
-- ---------------------------------------------------------------------------
create table if not exists public.venues (
  id          integer generated by default as identity primary key,
  name        varchar(255) not null unique,
  address     varchar(255),
  website     varchar(255),
  latitude    numeric(9, 6),
  longitude   numeric(9, 6),
  created_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- events — live, publicly visible events
-- ---------------------------------------------------------------------------
create table if not exists public.events (
  id             bigint generated always as identity primary key,
  created_at     timestamptz not null default now(),
  "desc"         text not null,
  "when"         text not null,
  special_price  text,
  event_time     text,
  venue_id       integer references public.venues (id) on update cascade on delete cascade
);

create index if not exists events_venue_id_idx on public.events (venue_id);

-- ---------------------------------------------------------------------------
-- events_pending — submissions from anonymous users, awaiting moderation
-- ---------------------------------------------------------------------------
create table if not exists public.events_pending (
  id             bigint generated always as identity primary key,
  created_at     timestamptz not null default now(),
  "desc"         text not null,
  "when"         text not null,
  special_price  text,
  event_time     text,
  venue_id       integer references public.venues (id) on update cascade on delete cascade
);

create index if not exists events_pending_venue_id_idx on public.events_pending (venue_id);

-- ---------------------------------------------------------------------------
-- issues — reports against an existing event
-- ---------------------------------------------------------------------------
create table if not exists public.issues (
  id          bigint generated always as identity primary key,
  created_at  timestamptz not null default now(),
  event_id    bigint references public.events (id) on delete cascade,
  issue       text,
  info        text
);

create index if not exists issues_event_id_idx on public.issues (event_id);

-- ---------------------------------------------------------------------------
-- feedback — general site feedback
-- ---------------------------------------------------------------------------
create table if not exists public.feedback (
  id          bigint generated always as identity primary key,
  created_at  timestamptz not null default now(),
  name        text,
  email       text,
  message     text not null
);

-- ---------------------------------------------------------------------------
-- Row Level Security
--
-- The old database only had RLS on `events`, while every table was granted
-- ALL to `anon` — meaning anonymous visitors could delete venues and read all
-- submitted feedback. RLS is enabled on every table here instead, and each
-- table gets only the policies the app actually needs.
-- ---------------------------------------------------------------------------
alter table public.venues         enable row level security;
alter table public.events         enable row level security;
alter table public.events_pending enable row level security;
alter table public.issues         enable row level security;
alter table public.feedback       enable row level security;

-- venues: world readable; anyone may add one (VenueComboBox), only signed-in
-- users may change or remove one.
create policy "venues are readable by everyone"
  on public.venues for select
  to anon, authenticated
  using (true);

create policy "anyone can add a venue"
  on public.venues for insert
  to anon, authenticated
  with check (true);

create policy "authenticated users can update venues"
  on public.venues for update
  to authenticated
  using (true) with check (true);

create policy "authenticated users can delete venues"
  on public.venues for delete
  to authenticated
  using (true);

-- events: world readable, but only signed-in users can write. Anonymous
-- submissions go to events_pending instead.
create policy "events are readable by everyone"
  on public.events for select
  to anon, authenticated
  using (true);

create policy "authenticated users can insert events"
  on public.events for insert
  to authenticated
  with check (true);

create policy "authenticated users can update events"
  on public.events for update
  to authenticated
  using (true) with check (true);

create policy "authenticated users can delete events"
  on public.events for delete
  to authenticated
  using (true);

-- events_pending: write-only for the public — anyone can submit, only
-- signed-in moderators can read the queue or clear it.
create policy "anyone can submit a pending event"
  on public.events_pending for insert
  to anon, authenticated
  with check (true);

create policy "authenticated users can read pending events"
  on public.events_pending for select
  to authenticated
  using (true);

create policy "authenticated users can delete pending events"
  on public.events_pending for delete
  to authenticated
  using (true);

-- issues: write-only for the public.
create policy "anyone can report an issue"
  on public.issues for insert
  to anon, authenticated
  with check (true);

create policy "authenticated users can read issues"
  on public.issues for select
  to authenticated
  using (true);

create policy "authenticated users can delete issues"
  on public.issues for delete
  to authenticated
  using (true);

-- feedback: write-only for the public. Contains names and email addresses,
-- so it must never be readable by anon.
create policy "anyone can submit feedback"
  on public.feedback for insert
  to anon, authenticated
  with check (true);

create policy "authenticated users can read feedback"
  on public.feedback for select
  to authenticated
  using (true);

create policy "authenticated users can delete feedback"
  on public.feedback for delete
  to authenticated
  using (true);
